[
  {
    "Submission Date": "2015-07-01 20:57:51",
    "First name": "Lucas",
    "Last name": "DeSantis",
    "High school": "Colorado Academy",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "LHP",
    "Height": 0,
    "Weight": 0,
    "College": "University of the South Sewanee",
    "Division": "NCAA D-3",
    "Commitment": "Verbal",
    "Date of commitment": 0
  },
  {
    "Submission Date": "2015-07-01 20:59:05",
    "First name": "Tyler",
    "Last name": "Reynolds",
    "High school": "Regis Jesuit",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (boys)",
    "Position": "Defense",
    "Height": 0,
    "Weight": 0,
    "College": "Sacred Heart",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": 0
  },
  {
    "Submission Date": "2015-07-02 08:30:54",
    "First name": "Keaton",
    "Last name": "Komatz",
    "High school": "Heritage",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (boys)",
    "Position": "Midfield",
    "Height": "6-0",
    "Weight": 175,
    "College": "Notre Dame",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "07-01-2014"
  },
  {
    "Submission Date": "2015-07-02 09:18:16",
    "First name": "Courtney",
    "Last name": "Ewing",
    "High school": "Pueblo West",
    "HS graduation year": 2015,
    "Sport": "Golf (girls)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Division": "NCAA D-2",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "11-24-2014"
  },
  {
    "Submission Date": "2015-07-02 09:21:22",
    "First name": "Tori",
    "Last name": "Goodman",
    "High school": "Falcon",
    "HS graduation year": 2015,
    "Sport": "Golf (girls)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Division": "NCAA D-2",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "11-24-2014"
  },
  {
    "Submission Date": "2015-07-02 09:25:31",
    "First name": "Taylor",
    "Last name": "Rodriguez",
    "High school": "South",
    "HS graduation year": 2015,
    "Sport": "Golf (boys)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Division": "NCAA D-2",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "11-24-2014"
  },
  {
    "Submission Date": "2015-07-02 09:27:36",
    "First name": "Roy",
    "Last name": "Carlsen",
    "High school": "Ralston Valley",
    "HS graduation year": 2015,
    "Sport": "Golf (boys)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Division": "NCAA D-2",
    "Commitment": "Verbal",
    "Date of commitment": "05-01-2015"
  },
  {
    "Submission Date": "2015-07-02 13:13:35",
    "First name": "Abbey",
    "Last name": "Wehrman",
    "High school": "Valley",
    "HS graduation year": 2015,
    "Sport": "Volleyball",
    "Position": "DS",
    "Height": "5-4",
    "Weight": 125,
    "College": "Otero Junior College",
    "Division": "JUCO",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "03-20-2015"
  },
  {
    "Submission Date": "2015-07-02 16:37:46",
    "First name": "Jack",
    "Last name": "Parsons",
    "High school": "Grand Junction",
    "HS graduation year": 2015,
    "Sport": "Football",
    "Position": "WR/DB",
    "Height": "6-0",
    "Weight": 165,
    "College": "Fort Lewis College",
    "Division": "NCAA D-2",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "01-21-2015"
  },
  {
    "Submission Date": "2015-07-02 17:07:52",
    "First name": "Mitchell",
    "Last name": "Martin",
    "High school": "Strasburg",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "QB",
    "Height": "6-3",
    "Weight": 195,
    "College": "Sioux Falls",
    "Division": "NCAA D-2",
    "Commitment": "Verbal",
    "Date of commitment": "06-23-2015"
  },
  {
    "Submission Date": "2015-07-02 20:13:59",
    "First name": "Regan",
    "Last name": "Kinney",
    "High school": "Cherry Creek",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (girls)",
    "Position": "Midfield",
    "Height": "5-11",
    "Weight": 128,
    "College": "Lafayette College",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "11-02-2014"
  },
  {
    "Submission Date": "2015-07-07 14:09:26",
    "First name": "Niko",
    "Last name": "Sangster",
    "High school": "Cherokee Trail",
    "HS graduation year": 2015,
    "Sport": "Football",
    "Position": "Defensive Tackle",
    "Height": "6-2",
    "Weight": 240,
    "College": "CSU-Pueblo",
    "Division": "NCAA D-2",
    "Commitment": "Verbal",
    "Date of commitment": "05-27-2015"
  },
  {
    "Submission Date": "2015-07-09 13:37:35",
    "First name": "Harrison",
    "Last name": "Stevens",
    "High school": "Eagle Valley",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "Outfield",
    "Height": "5-11",
    "Weight": 165,
    "College": "Colby Community College",
    "Division": "JUCO",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "04-24-2015"
  },
  {
    "Submission Date": "2015-07-10 16:49:21",
    "First name": "Grant",
    "Last name": "Witherspoon",
    "High school": "D'Evelyn",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "OF/LHP",
    "Height": "6-3",
    "Weight": 185,
    "College": "Tulane",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "07-09-2015"
  },
  {
    "Submission Date": "2015-07-10 19:18:47",
    "First name": "Anna",
    "Last name": "Hortik",
    "High school": "Cheyenne Mountain",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (girls)",
    "Position": "Midfield",
    "Height": "5-11",
    "Weight": 145,
    "College": "University of Denver",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "08-05-2014"
  },
  {
    "Submission Date": "7/17/2015 13:56:38",
    "First name": "Will",
    "Last name": "Rogan",
    "High school": "Bishop Machebeuf",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "1B",
    "Height": "6-4",
    "Weight": 195,
    "College": "Loras College",
    "Division": "NCAA D-3",
    "Commitment": "Verbal",
    "Date of commitment": "05-05-2015"
  },
  {
    "Submission Date": "7/19/2015 12:40:02",
    "First name": "Carter",
    "Last name": "Van Gytenbeek",
    "High school": "Cherry Creek",
    "HS graduation year": 2016,
    "Sport": "Baseball",
    "Position": "Pitcher",
    "Height": "6-1",
    "Weight": 190,
    "College": "West Point",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "12-01-2014"
  },
  {
    "Submission Date": "8/3/2015 13:13:15",
    "First name": "Connor",
    "Last name": "Sinks",
    "High school": "Regis Jesuit",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "LHP",
    "Height": "6-2",
    "Weight": 205,
    "College": "Garden City Community College",
    "Division": "JUCO",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "06-18-2015"
  },
  {
    "Submission Date": "2015-09-05 21:54:24",
    "First name": "Dylan",
    "Last name": "Cavey",
    "High school": "Cherry Creek",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "3rd/2nd Base",
    "Height": "6-0",
    "Weight": 180,
    "College": "Northwest Missouri State",
    "Division": "NCAA D-2",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "07-27-2015"
  },
  {
    "Submission Date": "2015-09-07 10:52:54",
    "First name": "Cole",
    "Last name": "Poyfair",
    "High school": "Kent Denver/Loomis Chaffee",
    "HS graduation year": 2015,
    "Sport": "Lacrosse (boys)",
    "Position": "Goalie",
    "Height": "6-3",
    "Weight": 185,
    "College": "Denison",
    "Division": "NCAA D-3",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "03-07-2015"
  },
  {
    "Submission Date": "2015-09-09 14:37:23",
    "First name": "Alex",
    "Last name": "Jackson",
    "High school": "Arapahoe",
    "HS graduation year": 2016,
    "Sport": "Soccer (boys)",
    "Position": "Defender",
    "Height": "6-0",
    "Weight": 150,
    "College": "Naval Academy",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "04-29-2015"
  },
  {
    "Submission Date": "2015-09-09 14:39:20",
    "First name": "Ryan",
    "Last name": "Sailor",
    "High school": "Arapahoe",
    "HS graduation year": 2016,
    "Sport": "Soccer (boys)",
    "Position": "Defender",
    "Height": "6-4",
    "Weight": 190,
    "College": "Washington",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "09-04-2015"
  },
  {
    "Submission Date": "2015-09-14 17:33:45",
    "First name": "Sara",
    "Last name": "McGuire",
    "High school": "Cherry Creek",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (girls)",
    "Position": "Goalie",
    "Height": "5-8",
    "Weight": 135,
    "College": "Winthrop",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "08-02-2015"
  },
  {
    "Submission Date": "2015-09-19 09:57:10",
    "First name": "Holly",
    "Last name": "Brooks",
    "High school": "Montrose",
    "HS graduation year": 2016,
    "Sport": "Basketball (girls)",
    "Position": "Point Guard/Shooting Guard",
    "Height": "5-6",
    "Weight": 127,
    "College": "Colorado Mesa",
    "Division": "NCAA D-2",
    "Commitment": "Verbal",
    "Date of commitment": "09-09-2015"
  },
  {
    "Submission Date": "2015-09-22 21:38:14",
    "First name": "Austin",
    "Last name": "Wood",
    "High school": "Silver Creek",
    "HS graduation year": 2016,
    "Sport": "Baseball",
    "Position": "RHP",
    "Height": "6-5",
    "Weight": 210,
    "College": "Furman",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "09-03-2015"
  },
  {
    "Submission Date": "2015-09-25 16:47:35",
    "First name": "Symone",
    "Last name": "Starks",
    "High school": "Highlands Ranch",
    "HS graduation year": 2016,
    "Sport": "Basketball (girls)",
    "Position": "Point Guard",
    "Height": "5-5",
    "Weight": 138,
    "College": "Eastern Washington",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "09-20-2015"
  },
  {
    "Submission Date": "2015-09-29 14:10:05",
    "First name": "Tayler",
    "Last name": "Philman",
    "High school": "Horizon",
    "HS graduation year": 2017,
    "Sport": "Soccer (girls)",
    "Position": "Goalie",
    "Height": "6-7",
    "Weight": 156,
    "College": "Summit Christian College",
    "Division": 0,
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "09-29-2015"
  },
  {
    "Submission Date": "2015-09-30 13:41:12",
    "First name": "McKenna",
    "Last name": "Bishop",
    "High school": "Lakewood",
    "HS graduation year": 2016,
    "Sport": "Basketball (girls)",
    "Position": "Forward",
    "Height": "6-0",
    "Weight": 150,
    "College": "Regis",
    "Division": "NCAA D-2",
    "Commitment": "Verbal",
    "Date of commitment": "09-14-2015"
  },
  {
    "Submission Date": "2015-10-01 22:46:58",
    "First name": "Jake",
    "Last name": "Rudel",
    "High school": "Fort Collins",
    "HS graduation year": 2016,
    "Sport": "Soccer (boys)",
    "Position": "Forward / Defense",
    "Height": "6-3",
    "Weight": 160,
    "College": "Saint Mary's College",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "08-01-2015"
  },
  {
    "Submission Date": "2015-10-07 18:34:44",
    "First name": "Cooper",
    "Last name": "Rothe",
    "High school": "Longmont",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "K/DB",
    "Height": "6-0",
    "Weight": 170,
    "College": "Wyoming",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "10-06-2015"
  },
  {
    "Submission Date": "2015-10-07 19:35:49",
    "First name": "Morgan",
    "Last name": "Gray",
    "High school": "Holy Family",
    "HS graduation year": 2016,
    "Sport": "Soccer (girls)",
    "Position": "Center Back",
    "Height": "6-1",
    "Weight": 160,
    "College": "Wingate",
    "Division": "NCAA D-2",
    "Commitment": "Verbal",
    "Date of commitment": "09-15-2015"
  },
  {
    "Submission Date": "2015-10-07 20:22:58",
    "First name": "Jackson",
    "Last name": "Solem",
    "High school": "Longmont Christian / Silver Creek",
    "HS graduation year": 2017,
    "Sport": "Golf (boys)",
    "Position": "na",
    "Height": "6-2",
    "Weight": 200,
    "College": "University of Denver",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "09-14-2015"
  },
  {
    "Submission Date": "2015-10-08 15:14:41",
    "First name": "Matt",
    "Last name": "Lynch",
    "High school": "Legacy",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "QB",
    "Height": "6-5",
    "Weight": 185,
    "College": "UCLA",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "05-06-2015"
  },
  {
    "Submission Date": "2015-10-08 15:16:55",
    "First name": "Terriek",
    "Last name": "Roberts",
    "High school": "Denver South",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "OT",
    "Height": "6-6",
    "Weight": 255,
    "College": "Colorado",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-02-2015"
  },
  {
    "Submission Date": "2015-10-08 15:18:22",
    "First name": "Jack",
    "Last name": "Stoll",
    "High school": "Regis Jesuit",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "TE",
    "Height": "6-4",
    "Weight": 220,
    "College": "Nebraska",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-24-2015"
  },
  {
    "Submission Date": "2015-10-08 15:19:32",
    "First name": "JoJo",
    "Last name": "Domann",
    "High school": "Pine Creek",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "OLB",
    "Height": "6-1",
    "Weight": 210,
    "College": "Nebraska",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-26-2015"
  },
  {
    "Submission Date": "2015-10-08 15:20:55",
    "First name": "Dillon",
    "Last name": "Reinkensmeyer",
    "High school": "Valor Christian",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "OT",
    "Height": "6-6",
    "Weight": 270,
    "College": "Virginia",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-29-2015"
  },
  {
    "Submission Date": "2015-10-08 15:22:21",
    "First name": "Jake",
    "Last name": "Moretti",
    "High school": "Pomona",
    "HS graduation year": 2017,
    "Sport": "Football",
    "Position": "OT",
    "Height": "6-5",
    "Weight": 285,
    "College": "Ohio State",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "07-04-2015"
  },
  {
    "Submission Date": "2015-10-08 15:24:18",
    "First name": "Tony",
    "Last name": "McBride",
    "High school": "Fort Morgan",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "RB/DE",
    "Height": "6-3",
    "Weight": 245,
    "College": "Colorado State",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "08-04-2015"
  },
  {
    "Submission Date": "2015-10-08 15:42:17",
    "First name": "Isiah",
    "Last name": "Pannunzio",
    "High school": "Pueblo South",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "TE/DE",
    "Height": "6-2",
    "Weight": 205,
    "College": "Colorado State",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "07-24-2015"
  },
  {
    "Submission Date": "2015-10-08 15:46:32",
    "First name": "Javen",
    "Last name": "Gumber",
    "High school": "Fruita Monument",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": "Forward",
    "Height": "6-7",
    "Weight": 165,
    "College": "Air Force Academy",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-24-2015"
  },
  {
    "Submission Date": "2015-10-08 15:48:03",
    "First name": "Austin",
    "Last name": "Mueller",
    "High school": "ThunderRidge",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": "Small forward",
    "Height": "6-6",
    "Weight": 190,
    "College": "Wyoming",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-17-2015"
  },
  {
    "Submission Date": "2015-10-08 15:50:02",
    "First name": "Justin",
    "Last name": "Bassey",
    "High school": "Colorado Academy",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": 2016,
    "Height": "6-4",
    "Weight": 200,
    "College": "Harvard",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "03-25-2015"
  },
  {
    "Submission Date": "2015-10-08 15:53:08",
    "First name": "Mike",
    "Last name": "Ranson",
    "High school": "Pueblo Central",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": "Guard",
    "Height": "6-2",
    "Weight": 185,
    "College": "Northern Colorado",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-17-2015"
  },
  {
    "Submission Date": "2015-10-08 15:58:45",
    "First name": "Ace",
    "Last name": "Escobedo",
    "High school": "Regis Jesuit",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "DL",
    "Height": "6-3",
    "Weight": 270,
    "College": "Pennsylvania",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "08-19-2015"
  },
  {
    "Submission Date": "2015-10-08 16:00:58",
    "First name": "Luke",
    "Last name": "Neff",
    "High school": "Arvada West",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": "Combo guard",
    "Height": "6-0",
    "Weight": 145,
    "College": "Universtiy of Denver",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "06-30-2015"
  },
  {
    "Submission Date": "2015-10-08 16:58:54",
    "First name": "Kobi",
    "Last name": "Betts",
    "High school": "Pueblo Central",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": "PG/SG",
    "Height": "6-4",
    "Weight": 185,
    "College": "Air Force Academy",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "08-19-2015"
  },
  {
    "Submission Date": "2015-10-08 17:00:32",
    "First name": "Justinian",
    "Last name": "Jessup",
    "High school": "Longmont",
    "HS graduation year": 2016,
    "Sport": "Basketball (boys)",
    "Position": "SG",
    "Height": "6-4",
    "Weight": 180,
    "College": "Boise State",
    "Division": "NCAA D-1",
    "Commitment": "Verbal",
    "Date of commitment": "09-12-2015"
  }
]