[
  {
    "Submission Date": "2015-07-01 20:57:51",
    "First name": "Lucas",
    "Last name": "DeSantis",
    "High school": "Colorado Academy",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "LHP",
    "Height": 0,
    "Weight": 0,
    "College": "University of the South Sewanee",
    "Commitment": "Verbal",
    "Date of commitment": 0,
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-01 20:59:05",
    "First name": "Tyler",
    "Last name": "Reynolds",
    "High school": "Regis Jesuit",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (boys)",
    "Position": "Defense",
    "Height": 0,
    "Weight": 0,
    "College": "Sacred Heart",
    "Commitment": "Verbal",
    "Date of commitment": 0,
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 08:30:54",
    "First name": "Keaton",
    "Last name": "Komatz",
    "High school": "Heritage",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (boys)",
    "Position": "Midfield",
    "Height": "6-0",
    "Weight": 175,
    "College": "Notre Dame",
    "Commitment": "Verbal",
    "Date of commitment": "07-01-2014",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 09:18:16",
    "First name": "Courtney",
    "Last name": "Ewing",
    "High school": "Pueblo West",
    "HS graduation year": 2015,
    "Sport": "Golf (girls)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "11-24-2014",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 09:21:22",
    "First name": "Tori",
    "Last name": "Goodman",
    "High school": "Falcon",
    "HS graduation year": 2015,
    "Sport": "Golf (girls)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "11-24-2014",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 09:25:31",
    "First name": "Taylor",
    "Last name": "Rodriguez",
    "High school": "South",
    "HS graduation year": 2015,
    "Sport": "Golf (boys)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "11-24-2014",
    "Other information": "2014 Colorado 4A State Champion",
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 09:27:36",
    "First name": "Roy",
    "Last name": "Carlsen",
    "High school": "Ralston Valley",
    "HS graduation year": 2015,
    "Sport": "Golf (boys)",
    "Position": "NA",
    "Height": 0,
    "Weight": 0,
    "College": "CSU-Pueblo",
    "Commitment": "Verbal",
    "Date of commitment": "05-01-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 13:13:35",
    "First name": "Abbey",
    "Last name": "Wehrman",
    "High school": "Valley",
    "HS graduation year": 2015,
    "Sport": "Volleyball",
    "Position": "DS",
    "Height": "5-4",
    "Weight": 125,
    "College": "Otero Junior College",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "03-20-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-02 16:37:46",
    "First name": "Jack",
    "Last name": "Parsons",
    "High school": "Grand Junction",
    "HS graduation year": 2015,
    "Sport": "Football",
    "Position": "WR/DB",
    "Height": "6-0",
    "Weight": 165,
    "College": "Fort Lewis College",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "01-21-2015",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/311678657971804619/image.jpg"
  },
  {
    "Submission Date": "2015-07-02 17:07:52",
    "First name": "Mitchell",
    "Last name": "Martin",
    "High school": "Strasburg",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "QB",
    "Height": "6-3",
    "Weight": 195,
    "College": "University of Sioux Falls",
    "Commitment": "Verbal",
    "Date of commitment": "06-23-2015",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/311680464521502243/image.jpg"
  },
  {
    "Submission Date": "2015-07-02 20:13:59",
    "First name": "Regan",
    "Last name": "Kinney",
    "High school": "Cherry Creek",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (girls)",
    "Position": "Midfield",
    "Height": "5-11",
    "Weight": 128,
    "College": "Lafayette College",
    "Commitment": "Verbal",
    "Date of commitment": "11-02-2014",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-07 14:09:26",
    "First name": "Niko",
    "Last name": "Sangster",
    "High school": "Cherokee Trail",
    "HS graduation year": 2015,
    "Sport": "Football",
    "Position": "Defensive Tackle",
    "Height": "6-2",
    "Weight": 240,
    "College": "CSU-Pueblo",
    "Commitment": "Verbal",
    "Date of commitment": "05-27-2015",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/312101766742536223/CTHS%20Football%20Senior%20Night%20%2866%29.JPG"
  },
  {
    "Submission Date": "2015-07-09 13:37:35",
    "First name": "Harrison",
    "Last name": "Stevens",
    "High school": "Eagle Valley",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "Outfield",
    "Height": "5-11",
    "Weight": 165,
    "College": "Colby Community College",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "04-24-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-10 16:49:21",
    "First name": "Grant",
    "Last name": "Witherspoon",
    "High school": "D'Evelyn",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "OF/LHP",
    "Height": "6-3",
    "Weight": 185,
    "College": "Tulane University",
    "Commitment": "Verbal",
    "Date of commitment": "07-09-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-07-10 19:18:47",
    "First name": "Anna",
    "Last name": "Hortik",
    "High school": "Cheyenne Mountain",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (girls)",
    "Position": "Midfield",
    "Height": "5-11",
    "Weight": 145,
    "College": "University of Denver",
    "Commitment": "Verbal",
    "Date of commitment": "08-05-2014",
    "Other information": "Multi-sport athlete. Didn't start playing lacrosse till the summer before high school.",
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/312379525354806809/Anna%20Hortik%20-%20DU%202020.jpg"
  },
  {
    "Submission Date": "7/15/2015 20:47:40",
    "First name": "Jericho",
    "Last name": "Simon",
    "High school": "Denver West",
    "HS graduation year": 2016,
    "Sport": "Football",
    "Position": "Lineman",
    "Height": "6-3",
    "Weight": 255,
    "College": "University of Michigan",
    "Commitment": "Verbal",
    "Date of commitment": "07-13-2015",
    "Other information": "Talented lineman commits to the Wolverines...Also had many D-1 offers.",
    "Upload photo": 0
  },
  {
    "Submission Date": "7/17/2015 13:56:38",
    "First name": "Will",
    "Last name": "Rogan",
    "High school": "Bishop Machebeuf",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "1B",
    "Height": "6-4",
    "Weight": 195,
    "College": "Loras College",
    "Commitment": "Verbal",
    "Date of commitment": "05-05-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "7/19/2015 12:40:02",
    "First name": "Carter",
    "Last name": "Van Gytenbeek",
    "High school": "Cherry Creek",
    "HS graduation year": 2016,
    "Sport": "Baseball",
    "Position": "Pitcher",
    "Height": "6-1",
    "Weight": 190,
    "College": "U.S. Military Academy (West Point)",
    "Commitment": "Verbal",
    "Date of commitment": "12-01-2014",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/313133198810286662/59416438-CCOV-119.jpg"
  },
  {
    "Submission Date": "8/3/2015 13:13:15",
    "First name": "Connor",
    "Last name": "Sinks",
    "High school": "Regis Jesuit",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "LHP",
    "Height": "6-2",
    "Weight": 205,
    "College": "Garden City Community College",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "06-18-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-09-05 21:54:24",
    "First name": "Dylan",
    "Last name": "Cavey",
    "High school": "Cherry Creek",
    "HS graduation year": 2015,
    "Sport": "Baseball",
    "Position": "3rd/2nd Base",
    "Height": "6-0",
    "Weight": 180,
    "College": "Northwest Missouri State University",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "07-27-2015",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/317313673122420853/Dylan Signing NLI.jpg"
  },
  {
    "Submission Date": "2015-09-07 10:52:54",
    "First name": "Cole",
    "Last name": "Poyfair",
    "High school": "Kent Denver/Loomis Chaffee",
    "HS graduation year": 2015,
    "Sport": "Lacrosse (boys)",
    "Position": "Goalie",
    "Height": "6-3",
    "Weight": 185,
    "College": "Denison University",
    "Commitment": "Signed Letter of Intent",
    "Date of commitment": "03-07-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-09-09 00:39:16",
    "First name": "Austin",
    "Last name": "Wood",
    "High school": "Silver Creek",
    "HS graduation year": 2016,
    "Sport": "Baseball",
    "Position": "RHP",
    "Height": "6-5",
    "Weight": 200,
    "College": "Furman University",
    "Commitment": "Verbal",
    "Date of commitment": "09-01-2015",
    "Other information": "Was also one of the top QB recruits in the state...",
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/317582769261161245/image.jpg"
  },
  {
    "Submission Date": "2015-09-09 14:37:23",
    "First name": "Alex",
    "Last name": "Jackson",
    "High school": "Arapahoe",
    "HS graduation year": 2016,
    "Sport": "Soccer (boys)",
    "Position": "Defender",
    "Height": "6-0",
    "Weight": 150,
    "College": "U.S. Naval Academy",
    "Commitment": "Verbal",
    "Date of commitment": "04-29-2015",
    "Other information": "First female in Arapahoe High School History to attend Naval Academy.",
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-09-09 14:39:20",
    "First name": "Ryan",
    "Last name": "Sailor",
    "High school": "Arapahoe",
    "HS graduation year": 2016,
    "Sport": "Soccer (boys)",
    "Position": "Defender",
    "Height": "6-4",
    "Weight": 190,
    "College": "University of Washington",
    "Commitment": "Verbal",
    "Date of commitment": "09-04-2015",
    "Other information": 0,
    "Upload photo": 0
  },
  {
    "Submission Date": "2015-09-11 15:22:05",
    "First name": "Austin",
    "Last name": "Wood",
    "High school": "Silver Creek",
    "HS graduation year": 2016,
    "Sport": "Baseball",
    "Position": "RHP / 1B",
    "Height": "6-5",
    "Weight": 200,
    "College": "Furman University",
    "Commitment": "Verbal",
    "Date of commitment": "09-11-2015",
    "Other information": "One of the Top Two sport athletes in Colorado has given up playing football to focus on Baseball full time while committing to D-1 Furman University (Southern Conference).",
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/317808523203703151/image.jpg"
  },
  {
    "Submission Date": "2015-09-14 17:33:45",
    "First name": "Sara",
    "Last name": "McGuire",
    "High school": "Cherry Creek",
    "HS graduation year": 2016,
    "Sport": "Lacrosse (girls)",
    "Position": "Goalie",
    "Height": "5-8",
    "Weight": 135,
    "College": "Winthrop University",
    "Commitment": "Verbal",
    "Date of commitment": "08-02-2015",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/318075623601198351/Screen Shot 2015-09-14 at 3.32.52 PM.png"
  },
  {
    "Submission Date": "2015-09-19 09:57:10",
    "First name": "Holly",
    "Last name": "Brooks",
    "High school": "Montrose",
    "HS graduation year": 2016,
    "Sport": "Basketball (girls)",
    "Position": "Point Guard/Shooting Guard",
    "Height": "5-6",
    "Weight": 127,
    "College": "Colorado Mesa University",
    "Commitment": "Verbal",
    "Date of commitment": "09-09-2015",
    "Other information": 0,
    "Upload photo": "http://www.jotform.us/uploads/denverpostdata/50716566158158/318480225741686613/image.jpg"
  },
  {
    "Submission Date": "2015-09-22 21:38:14",
    "First name": "Austin",
    "Last name": "Wood",
    "High school": "Silver Creek",
    "HS graduation year": 2016,
    "Sport": "Baseball",
    "Position": "RHP",
    "Height": "6-5",
    "Weight": 210,
    "College": "Furman University",
    "Commitment": "Verbal",
    "Date of commitment": "09-03-2015",
    "Other information": "Austin was Academic First Team All State in Football (QB) & Baseball (RHP/1B) last year as a Junior #3 passer 4A/5A last year in yardage and 5-1 Pitching making First Team Northern Conference, Pitcher of the Year, and First Team Boco All Region Team.",
    "Upload photo": 0
  }
]