[
  {
    "First name":"Lucas",
    "Last name":"DeSantis",
    "High school":"Colorado Academy",
    "HS graduation year":2015,
    "Sport":"Baseball",
    "Position":"LHP",
    "Height":"",
    "Weight":"",
    "College":"University of the South Sewanee",
    "Commitment":"Verbal",
    "Date of commitment":"",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"ebiday@q.com",
    "Phone number":"3039022442",
    "Twitter handle":""
  },
  {
    "First name":"Tyler",
    "Last name":"Reynolds",
    "High school":"Regis Jesuit",
    "HS graduation year":2016,
    "Sport":"Lacrosse",
    "Position":"Defense",
    "Height":"",
    "Weight":"",
    "College":"Sacred Heart",
    "Commitment":"Verbal",
    "Date of commitment":"",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"daver_dbr@yahoo.com",
    "Phone number":"9706186186",
    "Twitter handle":""
  },
  {
    "First name":"Keaton",
    "Last name":"Komatz",
    "High school":"Heritage",
    "HS graduation year":2016,
    "Sport":"Lacrosse",
    "Position":"Midfield",
    "Height":"6'0\"",
    "Weight":"175",
    "College":"Notre Dame",
    "Commitment":"Verbal",
    "Date of commitment":"07-01-2014",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"",
    "Phone number":"3039449414",
    "Twitter handle":""
  },
  {
    "First name":"Courtney",
    "Last name":"Ewing",
    "High school":"Pueblo West",
    "HS graduation year":2015,
    "Sport":"Golf (girls)",
    "Position":"NA",
    "Height":"NA",
    "Weight":"NA",
    "College":"CSU-Pueblo",
    "Commitment":"Signed Letter of Intent",
    "Date of commitment":"11-24-2014",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"josh.koschke@csupueblo.edu",
    "Phone number":"7195492254",
    "Twitter handle":""
  },
  {
    "First name":"Tori",
    "Last name":"Goodman",
    "High school":"Falcon",
    "HS graduation year":2015,
    "Sport":"Golf (girls)",
    "Position":"NA",
    "Height":"NA",
    "Weight":"NA",
    "College":"CSU-Pueblo",
    "Commitment":"Signed Letter of Intent",
    "Date of commitment":"11-24-2014",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"josh.koschke@csupueblo.edu",
    "Phone number":"7195492254",
    "Twitter handle":""
  },
  {
    "First name":"Taylor",
    "Last name":"Rodriguez",
    "High school":"South HS",
    "HS graduation year":2015,
    "Sport":"Golf (boys)",
    "Position":"NA",
    "Height":"NA",
    "Weight":"NA",
    "College":"CSU-Pueblo",
    "Commitment":"Signed Letter of Intent",
    "Date of commitment":"11-24-2014",
    "Other information":"2014 Colorado 4A State Champion",
    "Upload photo":"",
    "E-mail address":"josh.koschke@csupueblo.edu",
    "Phone number":"7195492254",
    "Twitter handle":""
  },
  {
    "First name":"Roy",
    "Last name":"Carlsen",
    "High school":"Ralston Valley",
    "HS graduation year":2015,
    "Sport":"Mens Golf",
    "Position":"NA",
    "Height":"NA",
    "Weight":"NA",
    "College":"CSU-Pueblo",
    "Commitment":"Verbal",
    "Date of commitment":"05-01-2015",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"josh.koschke@csupueblo.edu",
    "Phone number":"7195492254",
    "Twitter handle":"@KoPackGolf"
  },
  {
    "First name":"Abbey",
    "Last name":"Wehrman",
    "High school":"Valley High School",
    "HS graduation year":2015,
    "Sport":"Volleyball",
    "Position":"DS",
    "Height":"5/4/2015",
    "Weight":"125",
    "College":"Otero Junior College",
    "Commitment":"Signed Letter of Intent",
    "Date of commitment":"03-20-2015",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"",
    "Phone number":"",
    "Twitter handle":""
  },
  {
    "First name":"Jack",
    "Last name":"Parsons",
    "High school":"Grand Junction",
    "HS graduation year":2015,
    "Sport":"Football",
    "Position":"WR/DB",
    "Height":"6-0",
    "Weight":"165",
    "College":"Fort Lewis College",
    "Commitment":"Signed Letter of Intent",
    "Date of commitment":"01-21-2015",
    "Other information":"",
    "Upload photo":"http://www.jotform.us/uploads/denverpostdata/50716566158158/311678657971804619/image.jpg",
    "E-mail address":"Jpar314@msn.com",
    "Phone number":"970-778-9159",
    "Twitter handle":"Jack4parsons"
  },
  {
    "First name":"Mitchell",
    "Last name":"Martin",
    "High school":"Strasburg High School",
    "HS graduation year":2016,
    "Sport":"Football",
    "Position":"QB",
    "Height":"6/3/2015",
    "Weight":"195",
    "College":"University of Sioux Falls",
    "Commitment":"Verbal",
    "Date of commitment":"06-23-2015",
    "Other information":"",
    "Upload photo":"http://www.jotform.us/uploads/denverpostdata/50716566158158/311680464521502243/image.jpg",
    "E-mail address":"mitchmartin1288@gmail.com",
    "Phone number":"(303) 489-9739",
    "Twitter handle":"@mitch_12_martin"
  },
  {
    "First name":"Regan",
    "Last name":"Kinney",
    "High school":"Cherry Creek High School",
    "HS graduation year":2016,
    "Sport":"Lacrosse",
    "Position":"Midfield",
    "Height":"5' - 11\"",
    "Weight":"128 lbs",
    "College":"Lafayette College",
    "Commitment":"Verbal",
    "Date of commitment":"11-02-2014",
    "Other information":"",
    "Upload photo":"",
    "E-mail address":"regan.kinney@comcast.net",
    "Phone number":"3037412855",
    "Twitter handle":""
  },
  {
    "First name":"Niko",
    "Last name":"Sangster",
    "High school":"Cherokee Trail",
    "HS graduation year":2015,
    "Sport":"Football",
    "Position":"Defensive Tackle",
    "Height":"6'2\"",
    "Weight":"240",
    "College":"Colorado State University - Pueblo",
    "Commitment":"Verbal",
    "Date of commitment":"05-27-2015",
    "Other information":"",
    "Upload photo":"http://www.jotform.us/uploads/denverpostdata/50716566158158/312101766742536223/CTHS%20Football%20Senior%20Night%20%2866%29.JPG",
    "E-mail address":"sangster04@msn.com",
    "Phone number":"303-319-8738",
    "Twitter handle":""
  }
]
